#!/bin/sh -

# sudo echo $PID > /cpuset/exp/tasks

# IRQs
#   /proc/irq and /proc/interrupts
#   /etc/default/irqbalance
#      ENABLED="0"
#      reboot

# disable address-space randomization (ASR) via the following
#   sudo
#   cat /proc/sys/kernel/randomize_va_space
#   0 => disable, 2 => randomize stack positions
#   echo 0 > /proc/sys/kernel/randomize_va_space
#   echo 2 > /proc/sys/kernel/randomize_va_space
# set CPUs to maximum frequency
#   sudo
#   cpufreq-info  (lists information about all cores)
#   cpufreq-set --cpu 0 --min 2600000
#   ... for each even CPU (may work in pairs)
#   cpufreq-set --cpu 0 --min 1000000

Time=20 	# R x Time = length of experiment
N=32		# 1 to N threads tested

while [ ${#} -gt 0 ] ; do		# process command-line arguments
    case "${1}" in
	"Time="* | "N="* )
	    eval ${1}
	    ;;
	* )
	    # optional argument D is the degree of the tree (d-ary) for Zhang
	    Zhang=${1}
    esac
    shift				# remove argument
done

rm -rf core

T=1
while [ ${T} -le ${N} ] ; do
    ./a.out ${T} ${Time} ${Zhang}	# Zhang d-ary
    if [ -f core ] ; then
	echo core generated for ${T} ${Time}
	break
    fi
    T=`expr ${T} + 1`
done
