#!/bin/sh -

# Experiments for: MCS

# ARM -mno-outline-atomics => use LL/SC instead of calls to atomic routines: __aarch64_swp_acq_rel, __aarch64_cas8_acq_rel
# ARM -march=armv8.2-a+lse => generate Arm LSE extension instructions SWAP and CAS
# https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/making-the-most-of-the-arm-architecture-in-gcc-10

algorithms="MCS MCSFAS MCSK42 MCSH CLH HemLock QSpinLock PthreadLock SpinLock"
time=60
outdir=`hostname`
Exec=`hostname`.out
mkdir -p ${outdir}

if [ ${#} -ne 0 ] ; then
    algorithms="${@}"
fi

cflag="-Wall -Wextra -Werror -Wno-implicit-fallthrough -std=gnu11 -O3 -DNDEBUG -fno-reorder-functions -DPIN" #
if [ ${outdir} = "algol" ] ; then
    cflag=${cflag}" -mno-outline-atomics"	# use ARM LL/SC instructions for atomics
fi

runalgorithm() {
#    for atomic in "" "ATOMIC" ; do
    for atomic in "" ; do
	outfile=${outdir}/${1}${atomic}
	echo "${outfile}"
	gcc-10 ${cflag} ${atomic:+-D${atomic}} -D${outdir} -DAlgorithm=${1} -DNCS_DELAY=20 Harness.c -lpthread -lm -o ${outdir}.out
	./run1 Time=${time} Exec="${Exec}" > "${outfile}"
	if [ -f core ] ; then
	    echo core generated for ${1}
	    break
	fi
    done
}

rm -rf core
for algorithm in ${algorithms} ; do
    runalgorithm ${algorithm}
done

rm -f "${Exec}"
