#!/bin/sh -

algorithms2P="DekkerB DekkerRW Doran Peterson2 Tsay Kessels2"
algorithms2="DekkerOrig ${algorithms2P}"
algorithmsNP="PetersonBuhr TaubenfeldBuhr"
algorithmsN="LamportBakery MCS"
outdir=`hostname`
mkdir -p ${outdir}

if [ ${#} -ne 0 ] ; then
    algorithms="${@}"
fi

cflag="-Wall -Werror -std=gnu11 -g -O3 -DNDEBUG -fno-reorder-functions -DPIN" #

runalgorithm() {
    for flag in "" "FAST" ; do
	echo "${outdir}/${1}${3}${flag}"
	gcc ${cflag} ${flag:+-D${flag}} ${3:+-D${3}} -DAlgorithm=${1} Harness.c -lpthread -lm
	if [ ${2} -eq 2 ] ; then
	    ./run1 N=${2} T=2 > "${outdir}/${1}${3}${flag}"
	else
	    ./run1 N=${2} > "${outdir}/${1}${3}${flag}"
	fi
	if [ -f core ] ; then
	    echo core generated for ${1}
	    break
	fi
    done
}

rm -rf core
for algorithm in ${algorithms2} ; do
    runalgorithm ${algorithm} 2
done

for algorithm in ${algorithmsNP} ; do
    for algorithm2 in ${algorithms2P} ; do
	runalgorithm ${algorithm} 32 `echo ${algorithm2} | tr '[:lower:]' '[:upper:]'`
    done
done

for algorithm in ${algorithmsN} ; do
    runalgorithm ${algorithm} 32
done
