#!/bin/sh -

#algorithms="MCS TaubenfeldBuhr RMRS LamportBakery ElevatorSimple ElevatorQueue"
algorithms="ElevatorQueue"
outdir=`hostname`
mkdir -p ${outdir}

if [ ${#} -ne 0 ] ; then
    algorithms="${@}"
fi

cflag="-Wall -Werror -std=gnu11 -g -O3 -DNDEBUG -fno-reorder-functions -DPIN" #

runalgorithm() {
    for contention in "" "FAST" ; do
	echo "${outdir}/${1}${2}${3}${contention}"
	gcc ${cflag} ${contention:+-D${contention}} ${2:+-D${2}} ${3:+-D${3}} ${4:+-D${4}} -DAlgorithm=${1} Harness.c -lpthread -lm
	./run1 > "${outdir}/${1}${2}${3}${contention}"
	if [ -f core ] ; then
	    echo core generated for ${1}
	    break
	fi
    done
}

rm -rf core
for algorithm in ${algorithms} ; do
    if [ ${algorithm} = "ElevatorSimple" -o ${algorithm} = "ElevatorQueue" ] ; then
	for cas in "CAS" "WCasBL" "WCasLF" ; do
	    for flag in "" "FLAG" ; do
		runalgorithm ${algorithm} ${cas} ${flag}
	    done
	done
    else
	runalgorithm ${algorithm}
    fi
done

rm -f a.out
