#!/bin/sh -

algorithms="MCS TaubenfeldBuhr RMRS LamportBakery ElevatorBurns ElevatorSimple ElevatorQueue"
outdir=`hostname`
mkdir -p ${outdir}

if [ ${#} -ne 0 ] ; then
    algorithms="${@}"
fi

cflag="-Wall -Werror -std=gnu11 -g -O3 -DNDEBUG -fno-reorder-functions -DPIN" #

runalgorithm() {
    for flag in "" "FAST" ; do
	echo "${outdir}/${1}${2}${3}${flag}"
	gcc ${cflag} ${flag:+-D${flag}} ${2:+-D${2}} ${3:+-D${3}} ${4:+-D${4}} -DAlgorithm=${1} Harness.c -lpthread -lm
	./run1 > "${outdir}/${1}${2}${3}${flag}"
	if [ -f core ] ; then
	    echo core generated for ${1}
	    break
	fi
    done
}

rm -rf core
for algorithm in ${algorithms} ; do
    if [ ${algorithm} = "ElevatorSimple" ] ; then
	for cas in "CAS" "WCas1" "WCas2" ; do
	    runalgorithm ${algorithm} ${cas}
	done
    elif [ ${algorithm} = "ElevatorQueue" ] ; then
	for cas in "CAS" "WCas1" "WCas2" ; do
	    for sig in "" "FLAG" ; do
		runalgorithm ${algorithm} ${cas} ${sig}
	    done
	done
    else
	runalgorithm ${algorithm}
    fi
done
