#!/bin/sh -

algorithms2P="DekkerB DekkerRW Doran Peterson2 Tsay Kessels2"
algorithms2="DekkerOrig ${algorithms2P}"
algorithmsNP="PetersonBuhr TaubenfeldBuhr"
algorithmsN="LamportBakery MCS"
time=60
outdir=`hostname`
exec=`hostname`.out
atomicinst=

mkdir -p ${outdir}

if [ ${#} -ne 0 ] ; then
    algorithms="${@}"
fi

cflag="-Wall -Wextra -Werror -Wno-implicit-fallthrough -O3 -DNDEBUG -fno-reorder-functions -DPIN" #
if [ ${outdir} = "algol" -o ${outdir} = "prolog" ] ; then
#    atomicinst=-mno-outline-atomics	# use ARM LL/SC instructions for atomics
    atomicinst=-march=armv8.2-a+lse
    cflag=${cflag}" ${atomicinst} -DATOMIC"
fi

if [ "${outdir}" = "prolog" -o "${outdir}" = "swift" -o "${outdir}" = "java" ] ; then # Ubuntu 22.04
    CC=gcc-12
else
    CC=gcc-11
fi

runalgorithm() {
    for flag in "" "FAST" ; do
	outfile=${outdir}/${1}${3}${flag}
	echo "${outfile}"
	${CC} ${cflag} -std=gnu11 ${flag:+-D${flag}} ${3:+-D${3}} -DAlgorithm=${1} Harness.c -lpthread -lm -o ${exec}
	if [ ${2} -eq 2 ] ; then
	    ./run1 exec="${exec}" N=${2} T=2 > "${outdir}/${1}${3}${flag}"
	else
	    ./run1 exec="${exec}" N=${2} > "${outdir}/${1}${3}${flag}"
	fi
	if [ -f core ] ; then
	    echo core generated for ${1}
	    break
	fi
    done
}

rm -rf core
for algorithm in ${algorithms2} ; do
    runalgorithm ${algorithm} 2
done

for algorithm in ${algorithmsNP} ; do
    for algorithm2 in ${algorithms2P} ; do
	runalgorithm ${algorithm} 32 `echo ${algorithm2} | tr '[:lower:]' '[:upper:]'`
    done
done

for algorithm in ${algorithmsN} ; do
    runalgorithm ${algorithm} 32
done

rm -f "${exec}"
