#!/bin/sh -

# Experiments for: BW Bakery Algorithm

algorithms="LamportBakery Hehner Lycklama LycklamaBuhr TaubenfeldBWBakery HesselinkBWBakery HesselinkBWBakery2 MCS"
time=10
outdir=`hostname`
mkdir -p ${outdir}

if [ ${#} -ne 0 ] ; then
    algorithms="${@}"
fi

cflag="-Wall -Wextra -Werror -Wno-implicit-fallthrough -std=gnu11 -O3 -DNDEBUG -fno-reorder-functions -DPIN" #

runalgorithm() {
    for contention in "" "FAST" ; do
	outfile=${outdir}/${1}${2}${contention}
	echo "${outfile}"
	gcc-9 ${cflag} ${contention:+-D${contention}} -D${outdir} -DAlgorithm=${1} Harness.c -lpthread -lm
	./run1 Time=${time} > "${outfile}"
	if [ -f core ] ; then
	    echo core generated for ${1}
	    break
	fi
    done
}

rm -rf core
for algorithm in ${algorithms} ; do
    runalgorithm ${algorithm}
done

rm -f a.out
