#!/bin/sh -x

#zip Barrier.zip softsolutions/Barrier* softsolutions/Harness.c softsolutions/run1 softsolutions/runallBarrier 

# Experiments for: Barrier

# ARM -mno-outline-atomics => use LL/SC instead of calls to atomic routines: __aarch64_swp_acq_rel, __aarch64_cas8_acq_rel
# ARM -march=armv8.2-a+lse => generate Arm LSE extension instructions SWAP and CAS
# https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/making-the-most-of-the-arm-architecture-in-gcc-10

algorithms="BarrierButterfly BarrierDissem BarrierDissemMCS BarrierFai BarrierLeader BarrierPthread BarrierRing BarrierRingAravind BarrierSTD BarrierSenseRev \
	BarrierStack BarrierSym BarrierTour BarrierTourMCS BarrierTree BarrierTreeA BarrierTreeC BarrierTreeCombMCS BarrierTreeMCS"

time=30
runs=5
outdir=`hostname`
exec=${outdir}.out
atomicinst=
delay=0

mkdir -p ${outdir}

if [ ${#} -ne 0 ] ; then
    algorithms="${@}"
fi

cflag="-Wall -Wextra -Werror -Wno-implicit-fallthrough -O3 -DNDEBUG -fno-reorder-functions" #
if [ ${outdir} = "algol" -o ${outdir} = "prolog" ] ; then
#    atomicinst=-mno-outline-atomics	# use ARM LL/SC instructions for atomics
    atomicinst=-march=armv8.2-a+lse	# use ARM LSE instructions for atomics
    cflag=${cflag}" ${atomicinst} -DATOMIC"
fi

if [ "${outdir}" = "prolog" -o "${outdir}" = "swift" -o "${outdir}" = "plg2" -o "${outdir}" = "java" ] ; then # Ubuntu 24.04
    CC=gcc-14
else
    CC=gcc-11
fi

runalgorithm() {
    for atomic in "" ; do # "ATOMIC"
	for affinity in "PIN" "" ; do #
	    outfile=${outdir}${affinity}/${1}${atomic}
	    echo "${outfile}"
	    if [ ${1} = "BarrierSTD" ] ; then		# C++ barrier ?
		`echo ${CC} | tr cc ++` ${cflag} -Wno-volatile -std=c++20 ${affinity:+-D${affinity}} ${atomic:+-D${atomic}} ${atomicinst:+-DATOMICINST=${atomicinst}} -D${outdir} -DBARRIER -DAlgorithm=${1} -DNCS_DELAY="${delay}" Harness.c -lpthread -lm -o ${exec}
	    else
		${CC} ${cflag} -std=gnu11 ${affinity:+-D${affinity}} ${atomic:+-D${atomic}} ${atomicinst:+-DATOMICINST=${atomicinst}} -D${outdir} -DBARRIER -DAlgorithm=${1} -DNCS_DELAY="${delay}" Harness.c -lpthread -lm -o ${exec}
	    fi
	    ./run1 time="${time}" runs="${runs}" exec="${exec}" T=1 N=128 inc=2 > "${outfile}"
	    if [ -f core ] ; then
		echo core generated for ${1}
		break
	    fi
	done
    done
}

rm -rf core
for algorithm in ${algorithms} ; do
    rm -f ${exec}					# remove prior executable
    runalgorithm ${algorithm}
done

rm -f "${exec}"
