#!/bin/sh -

# Experiments for: Elevator Algorithm

algorithms="ElevatorLinear ElevatorLinear2 ElevatorTree ElevatorTree2 MCS RMRS"
time=5
outdir=`hostname`
exec=`hostname`.out

mkdir -p ${outdir}

if [ ${#} -ne 0 ] ; then
    algorithms="${@}"
fi

cflag="-Wall -Wextra -Werror -Wno-implicit-fallthrough -std=gnu11 -O3 -DNDEBUG -fno-reorder-functions -DPIN" #
if [ ${outdir} = "algol" -o ${outdir} = "prolog" ] ; then
#    atomicinst=-mno-outline-atomics	# use ARM LL/SC instructions for atomics
    atomicinst=-march=armv8.2-a+lse
    cflag=${cflag}" ${atomicinst} -DATOMIC"
fi

if [ "${outdir}" = "prolog" -o "${outdir}" = "swift" -o "${outdir}" = "java" ] ; then # Ubuntu 22.04
    CC=gcc-12
else
    CC=gcc-11
fi

runalgorithm() {
    for fast in "" "FAST" ; do
	outfile="${outdir}/${1}${2}${3}${4}${fast}"
	echo "${outfile}"
	${CC} ${cflag} ${fast:+-D${fast}} ${2:+-D${2}} ${3:+-D${3}} ${4:+-D${4}} ${5:+-D${5}} -DAlgorithm=${1} Harness.c -lpthread -lm -o ${exec}
	./run1 time=${time} exec="${exec}" runs=3 > "${outfile}"
	if [ -f core ] ; then
	    echo core generated for ${1}
	    rm -rf core
	    break
	fi
    done
}

for algorithm in ${algorithms} ; do
    case "${algorithm}" in
	"Elevator"*)
	    for cas in "CAS" "WCasBL" "WCasLF" ; do
		for flag in "" "FLAG" ; do
		    if [ ${algorithm} = "ElevatorLinear2" -o ${algorithm} = "ElevatorTree2" ] ; then
			for posn in "POSN1" "POSN2" ; do
			    runalgorithm ${algorithm} ${cas} ${flag} ${posn}
			done
		    else
			runalgorithm ${algorithm} ${cas} ${flag}
		    fi
		done
	    done
	    ;;
	*)
	    runalgorithm ${algorithm}
	    ;;
    esac
done

rm -f "${exec}"
