#!/bin/sh -

# Experiments for: Rectangle Algorithm

algorithms="Triangle TriangleMod Trapezium Rectangle MCS SpinLock SpinLockTicket"
outdir=`hostname`
mkdir -p ${outdir}

if [ ${#} -ne 0 ] ; then
    algorithms="${@}"
fi

cflag="-Wall -Wextra -Werror -Wno-implicit-fallthrough -std=gnu11 -g -O3 -DNDEBUG -fno-reorder-functions -DPIN" #

runalgorithm() {
    for contention in "" "FAST" ; do
	outfile=${outdir}/${1}${2}${contention}
	echo "${outfile}"
	gcc-11 ${cflag} ${contention:+-D${contention}} ${2:+-DNEST=${2}} -DAlgorithm=${1} Harness.c -lpthread -lm
	./run1 > "${outfile}"
	if [ -f core ] ; then
	    echo core generated for ${1}
	    break
	fi
    done
}

rm -rf core
for algorithm in ${algorithms} ; do
    if [ ${algorithm} = "Trapezium" -o ${algorithm} = "TrapeziumHW" ] ; then
	for K in 1 2 3 ; do # 4 5
	    runalgorithm ${algorithm} ${K}
	done
    else
	runalgorithm ${algorithm}
    fi
done

rm -f a.out
