#!/bin/sh -

algorithms="AndersonKim Aravind Burns2 BurnsLynchRetract DeBruijn DekkerA DekkerB DekkerC DekkerOrig DekkerRW Dijkstra Doran Eisenberg ElevatorBurns ElevatorQueue ElevatorSimple ElevatorSimple.noflag Hehner Hesselink Kessels Knuth LamportBakery LamportFast LamportRetract Lycklama LycklamaBuhr Lynch Peterson Peterson2 PetersonBuhr PetersonT RMRS Szymanski Szymanski2 Szymanski3 Taubenfeld TaubenfeldBuhr Triangle TriangleMod Zhang2T ZhangYA ZhangdT"

cflag="-Wall -Werror -O3 -DNDEBUG -I/u/pabuhr/software/relacy_2_4"

# rm -f core
# for algorithm in ${algorithms} ; do
#     g++ ${cflag} ${algorithm}.cc
#     ./a.out
#     if [ -f core ] ; then
# 	echo core generated for ${algorithm}
# 	break
#     fi
# done

#algorithms="ElevatorQueue"

runalgorithm() {
    echo "${1}${2}${3}"
    g++ ${cflag} ${2:+-D${2}} ${3:+-D${3}} ${4:+-D${4}} ${1}.cc
    ./a.out
    if [ -f core ] ; then
	echo core generated for ${1}
	break
    fi
}

rm -rf core
for algorithm in ${algorithms} ; do
    if [ ${algorithm} = "ElevatorSimple" -o ${algorithm} = "ElevatorSimple.noflag" -o ${algorithm} = "ElevatorQueue" ] ; then
	for cas in "CAS" "WCasBL" "WCasLF" ; do
	    for flag in "" "FLAG" ; do
		runalgorithm ${algorithm} ${cas} ${flag}
	    done
	done
    else
	runalgorithm ${algorithm}
    fi
done

rm -f a.out
